Repository unb-mds/2024-1-EducaMinas-backend, pull requests merged in 2024-08, with the labels that each got.

#20 Feat #17/ranking service
  api/src/database/memory/data/rankingMemoryData.ts
  api/src/database/memory/rankingRepositoryMemory.ts
  api/src/repositories/rankingRepository.ts
  api/src/services/rankingServices.spec.ts
  api/src/services/rankingServices.ts
Labels: feature, testing

#23 feat#22: implements supabase connection
  api/src/controllers/enrollmentController.ts
  api/src/index.ts
  package-lock.json
  package.json
Labels: enhancement, feature

#26 Feature#24/api documentation
  api/src/index.ts
  api/src/routes/enrollmentRoute.ts
  api/src/routes/indicatorRoute.ts
  api/src/routes/rankingRoute.ts
  api/src/swaggerConfig.ts
  package-lock.json
  package.json
Labels: documentation

#28 feat#27: includes nodemon to run api
  package-lock.json
  package.json
Labels: enhancement, performance

#32 Feat #30/static return
  api/src/controllers/enrollmentController.ts
  api/src/controllers/indicatorController.ts
  api/src/controllers/rankingController.ts
  api/src/routes/enrollmentRoute.ts
Labels: bug, feature

#29 Feature #16/indicators service
  api/src/database/memory/data/indicadoresMemoryData.ts
  api/src/database/memory/indicadoresRepositoryMemory.ts
  api/src/repositories/indicadoresRepository.ts
  api/src/services/indicadoresService.spec.ts
  api/src/services/indicadoresServices.ts
Labels: feature, testing

#34 feat: includes deploy configuration
  .gitignore
  api/src/index.ts
  vercel.json
Labels: enhancement

#35 Feature#33/deploy configuration
  api/src/index.ts
  api/src/swaggerConfig.ts
  package-lock.json
  package.json
  vercel.json
Labels: enhancement

#37 Feature#33/deploy configuration
  api/src/controllers/enrollmentController.ts
  api/src/controllers/indicatorController.ts
  api/src/controllers/rankingController.ts
  api/src/index.ts
Labels: enhancement

#38 feat#33: includes deploy express ci
  .github/workflows/deploy-express.yaml
  .github/workflows/quality.yaml
Labels: enhancement, feature, performance

#39 update main
  .editorconfig
  .eslintignore
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/sprint-tasks.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-express.yaml
  .github/workflows/quality.yaml
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  api/src/controllers/enrollmentController.ts
  api/src/controllers/indicatorController.ts
  api/src/controllers/rankingController.ts
  api/src/database/memory/data/indicadoresMemoryData.ts
  api/src/database/memory/data/matriculasMemoryData.ts
  api/src/database/memory/data/rankingMemoryData.ts
  api/src/database/memory/indicadoresRepositoryMemory.ts
  api/src/database/memory/matriculasRepositoryMemory.ts
  api/src/database/memory/rankingRepositoryMemory.ts
  api/src/index.ts
  api/src/repositories/indicadoresRepository.ts
  api/src/repositories/matriculasRepository.ts
  api/src/repositories/rankingRepository.ts
  api/src/routes/enrollmentRoute.ts
  api/src/routes/indicatorRoute.ts
  api/src/routes/rankingRoute.ts
  api/src/services/indicadoresService.spec.ts
  api/src/services/indicadoresServices.ts
  api/src/services/matriculasService.spec.ts
  api/src/services/matriculasServices.ts
  api/src/services/rankingServices.spec.ts
  api/src/services/rankingServices.ts
  api/src/swaggerConfig.ts
  package-lock.json
  package.json
  tsconfig.json
  vercel.json
  vitest.config.ts
Labels: enhancement

#40 Feature#33/deploy configuration
  .github/workflows/deploy-express.yaml
Labels: enhancement

#41 update main
  .github/workflows/deploy-express.yaml
Labels: enhancement

#48 feat#27: return nodemon configuration
  api/src/index.ts
  package.json
Labels: enhancement

#50 feat#49: includes pre commit tests
  package-lock.json
  package.json
Labels: enhancement, testing

#51 Feat #36/matriculas repository psql
  api/src/controllers/enrollmentController.ts
  api/src/database/memory/data/matriculasMemoryData.ts
  api/src/database/psql/matriculasRepositoryPSQL.ts
  api/src/services/matriculasService.spec.ts
  api/src/services/matriculasServices.ts
Labels: feature, testing

#52 deploy matriculas route
  api/src/controllers/enrollmentController.ts
  api/src/database/memory/data/matriculasMemoryData.ts
  api/src/database/psql/matriculasRepositoryPSQL.ts
  api/src/index.ts
  api/src/services/matriculasService.spec.ts
  api/src/services/matriculasServices.ts
  package-lock.json
  package.json
Labels: feature

#54 Feature#53/frontend align
  api/src/controllers/enrollmentController.ts
  api/src/controllers/indicatorController.ts
  api/src/controllers/rankingController.ts
  api/src/routes/rankingRoute.ts
  api/src/services/matriculasServices.ts
Labels: documentation, feature

#55 randomic static returns
  api/src/controllers/enrollmentController.ts
  api/src/controllers/indicatorController.ts
  api/src/controllers/rankingController.ts
  api/src/routes/rankingRoute.ts
  api/src/services/matriculasServices.ts
Labels: enhancement

#57 feat(#56): includes codecov on quality pipeline
  .github/workflows/quality.yaml
Labels: documentation, testing

#58 feat(#56): includes codecov
  .github/workflows/quality.yaml
  README.md
Labels: documentation, feature, testing

#60 Feat #59/ranking implementation
  api/src/controllers/rankingController.ts
  api/src/database/memory/data/rankingMemoryData.ts
  api/src/database/psql/rankingRepositoryPSQL.ts
  api/src/repositories/rankingRepository.ts
  api/src/services/rankingServices.spec.ts
  api/src/services/rankingServices.ts
Labels: feature, testing

#62 Feat #61/implement indicadores
  api/src/controllers/indicatorController.ts
  api/src/database/memory/data/indicadoresMemoryData.ts
  api/src/database/memory/indicadoresRepositoryMemory.ts
  api/src/database/psql/indicadoresRepositoryPSQL.ts
  api/src/repositories/indicadoresRepository.ts
  api/src/services/indicadoresService.spec.ts
  api/src/services/indicadoresServices.ts
  api/src/services/matriculasServices.ts
  api/src/services/rankingServices.spec.ts
Labels: bug, feature, testing

#63 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#65 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#64 Create SECURITY.md
  SECURITY.md
Labels: documentation

#66 merge develop
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  api/src/controllers/indicatorController.ts
  api/src/controllers/rankingController.ts
  api/src/database/memory/data/indicadoresMemoryData.ts
  api/src/database/memory/data/rankingMemoryData.ts
  api/src/database/memory/indicadoresRepositoryMemory.ts
  api/src/database/psql/indicadoresRepositoryPSQL.ts
  api/src/database/psql/rankingRepositoryPSQL.ts
  api/src/repositories/indicadoresRepository.ts
  api/src/repositories/rankingRepository.ts
  api/src/services/indicadoresService.spec.ts
  api/src/services/indicadoresServices.ts
  api/src/services/matriculasServices.ts
  api/src/services/rankingServices.spec.ts
  api/src/services/rankingServices.ts
Labels: bug, design, documentation, enhancement, feature, performance, testing
