Repository unb-mds/2024-1-EducaMinas-backend, pull requests merged in 2024-07, with the labels that each got.

#10 Feature #7/services
  api/src/database/memory/matriculasRepositoryMemory.ts
  api/src/repositories/matriculasRepository.ts
  api/src/services/matriculasServices.ts
Labels: feature

#14 Feature#11/implement tests
  .eslintignore
  .gitignore
  api/src/database/memory/matriculasRepositoryMemory.ts
  api/src/services/matriculasService.spec.ts
  api/src/services/matriculasServices.ts
  package-lock.json
  package.json
  tsconfig.json
  vitest.config.ts
Labels: enhancement, testing

#19 Feature #18/matriculas service ordenation
  api/src/database/memory/data/matriculasMemoryData.ts
  api/src/services/matriculasService.spec.ts
  api/src/services/matriculasServices.ts
Labels: feature, testing
